### ISSUE TITLE
Are the Backend API's public or private?

### ISSUE THREAD

**Issue by S2606** [Guzzler/Cowin-Notification-System#12]
Currently cannot find the Server URL from where data is fetched. Might become easier for other developers to contribute.

**Comment by Guzzler** [comment]
Hey @S2606, currently we arent exposing our endpoints largely because they act as a middleware to the official Co-WIN endpoints. But you are welcome to contribute as mentioned on our website we have both the frontend and backend repositories tagged. Feel free to raise a PR at either place!
