### ISSUE TITLE
Loader/Spinner on submitting subscription request looks weird

### ISSUE THREAD

**Issue by MrMathur** [Guzzler/Cowin-Notification-System#18]
https://user-images.githubusercontent.com/28644407/117533038-74999e80-afb8-11eb-9140-a9f321237db6.mov

**Comment by Guzzler** [comment]
weird not being able to reproduce. will take a look

**Comment by Guzzler** [comment]
have fixed this in PR https://github.com/Guzzler/Cowin-Notification-System/pull/17
