### ISSUE TITLE
Unsubscribe endpoint is broken - unsubscribe link in email points to just "unsub_endpoint/"

### ISSUE THREAD

**Issue by nikhilag** [Guzzler/Cowin-Notification-System#20]
![image](https://user-images.githubusercontent.com/54072321/120220428-55f69280-c25a-11eb-91ef-42045974549f.png)

**Comment by Guzzler** [comment]
@nikhilag A fix is in the works! thanks for pointing it out. Was due to some of the recent changes we made to the email template.

**Comment by Guzzler** [comment]
All new emails will have the fixed unsubscribe link. Closing this issue
